import type { AuditResponse } from "@/services/api";

export function generateReportHTML(data: AuditResponse, url: string): string {
  const counts = { pass: 0, fail: 0, warning: 0 };
  data.automated_results.forEach((r) => counts[r.result.status]++);
  const total = data.automated_results.length;
  const score = total > 0 ? Math.round((counts.pass / total) * 100) : 0;
  const date = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  const statusIcon = (s: string) =>
    s === "pass" ? "✅" : s === "fail" ? "❌" : "⚠️";

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Compliance Report — ${data.framework}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', system-ui, sans-serif; color: #1a1a2e; padding: 40px; max-width: 900px; margin: 0 auto; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    .subtitle { color: #666; font-size: 13px; margin-bottom: 32px; }
    .summary { display: flex; gap: 16px; margin-bottom: 32px; }
    .summary-card { flex: 1; padding: 16px; border-radius: 8px; border: 1px solid #e5e5e5; text-align: center; }
    .summary-card .value { font-size: 28px; font-weight: 700; }
    .summary-card .label { font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; margin-top: 4px; }
    .score-pass { color: #22c55e; }
    .score-fail { color: #ef4444; }
    .score-warn { color: #f59e0b; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 32px; font-size: 13px; }
    th { text-align: left; padding: 10px 12px; background: #f8f9fa; border-bottom: 2px solid #e5e5e5; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; color: #666; }
    td { padding: 10px 12px; border-bottom: 1px solid #f0f0f0; }
    tr:hover { background: #fafafa; }
    .section-title { font-size: 16px; font-weight: 600; margin-bottom: 12px; margin-top: 8px; }
    .mono { font-family: 'SF Mono', 'Consolas', monospace; font-size: 12px; }
    .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 16px; }
    @media print { body { padding: 20px; } .summary-card { break-inside: avoid; } }
  </style>
</head>
<body>
  <h1>🛡️ Compliance Report — ${data.framework}</h1>
  <p class="subtitle">Target: ${url} &nbsp;|&nbsp; Generated: ${date}</p>
  
  <div class="summary">
    <div class="summary-card">
      <div class="value ${score >= 80 ? "score-pass" : score >= 50 ? "score-warn" : "score-fail"}">${score}%</div>
      <div class="label">Compliance Score</div>
    </div>
    <div class="summary-card">
      <div class="value score-pass">${counts.pass}</div>
      <div class="label">Passed</div>
    </div>
    <div class="summary-card">
      <div class="value score-fail">${counts.fail}</div>
      <div class="label">Failed</div>
    </div>
    <div class="summary-card">
      <div class="value score-warn">${counts.warning}</div>
      <div class="label">Warnings</div>
    </div>
    <div class="summary-card">
      <div class="value">${data.manual_controls.length}</div>
      <div class="label">Manual Review</div>
    </div>
  </div>

  <p class="section-title">Automated Controls</p>
  <table>
    <thead>
      <tr><th>Control</th><th>Title</th><th>Status</th><th>Issue</th></tr>
    </thead>
    <tbody>
      ${data.automated_results
        .map(
          (r) =>
            `<tr><td class="mono">${r.control}</td><td>${r.title}</td><td>${statusIcon(r.result.status)} ${r.result.status.toUpperCase()}</td><td>${r.result.issue || "—"}</td></tr>`
        )
        .join("\n      ")}
    </tbody>
  </table>

  ${
    data.manual_controls.length > 0
      ? `<p class="section-title">Manual Controls</p>
  <table>
    <thead>
      <tr><th>Control</th><th>Title</th><th>Status</th></tr>
    </thead>
    <tbody>
      ${data.manual_controls
        .map(
          (c) =>
            `<tr><td class="mono">${c.control}</td><td>${c.title}</td><td>${c.status}</td></tr>`
        )
        .join("\n      ")}
    </tbody>
  </table>`
      : ""
  }

  <div class="footer">
    Generated by AuditAura — AI Compliance Agent
  </div>
</body>
</html>`;
}

export function downloadReport(data: AuditResponse, url: string) {
  const html = generateReportHTML(data, url);
  const blob = new Blob([html], { type: "text/html" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `compliance-report-${data.framework}-${new Date().toISOString().slice(0, 10)}.html`;
  a.click();
  URL.revokeObjectURL(a.href);
}

export function printReport(data: AuditResponse, url: string) {
  const html = generateReportHTML(data, url);
  const win = window.open("", "_blank");
  if (win) {
    win.document.write(html);
    win.document.close();
    setTimeout(() => win.print(), 500);
  }
}
